 language: node_js
 node_js:
   - "0.11"
   - "0.10"
 branches:
 only:
  - master
 notifications:
  email:
   - joaquim@yld.io
 script: npm test
 before_install:
   - npm install -g npm@~1.4.6
 services:
   - rabbitmq
   - redis-server